print('Составление анкеты:')
name = input('Введите ваше ФИО: ')
age = input('Укажите ваш возраст: ')
high = input('Укажите ваш рост(м): ')
weight = input('Укажите ваш вес(кг): ')
place1 = input('Укажите место вашего проживания: ')
print('Анкета:')
print('ФИО:', name)
print('Возраст:', age, "лет") 
print('Рост:', high, 'м')
print('Вес:', weight, 'кг')
print('Место проживания:', place1)
